const $ = s => document.querySelector(s);
const esc = (s='') => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const METRICS={pain:'Pain',frequency:'Frequency',economicLeverage:'Economic leverage',failureCost:'Failure cost',laborIntensity:'Labor intensity',fragmentation:'Fragmentation',aiLeverage:'AI leverage',distribution:'Distribution',dataAvailability:'Data availability',founderFit:'Founder fit',validation:'Validation'};

function parseLooseJson(text){let out='',inString=false,escaped=false;for(const c of text){if(inString){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')inString=false;else if(c==='\n'||c==='\r'){out+=c==='\n'?'\\n':'';continue;}}else if(c==='"')inString=true;out+=c;}return JSON.parse(out);}
async function loadJson(url){const text=await fetch(url).then(r=>{if(!r.ok)throw new Error(`${url} returned ${r.status}`);return r.text();});return parseLooseJson(text);}
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,v));

function normalizeIndustryOpportunity(o,weights){const base=Object.entries(weights).reduce((s,[k,w])=>s+((o.dimensions?.[k]||0)/5*w),0);const score=base-(o.riskPenalty||0);const priority=score*(.86+.028*(o.confidence||3));return {...o,baseScore:base,score,priorityScore:priority,evidence:o.evidence||[],riskNotes:o.riskNotes||[]};}
function normalizeCityOpportunity(o,weights){const base=Object.entries(weights).reduce((s,[k,w])=>s+((o.dimensions?.[k]||0)/5*w),0);const score=base-(o.riskPenalty||0);const priority=Number.isFinite(o.priorityScore)?o.priorityScore:score*(.85+.03*(o.confidence||3));return {...o,priorityScore:priority};}

async function loadIndustryAtlas(){const manifest=await loadJson('/data/industries-index.json');const shards=await Promise.all(manifest.shards.map(s=>loadJson(`/data/${s}`)));const detail=new Map(shards.flat().map(x=>[x.slug,x.opportunities.map(o=>normalizeIndustryOpportunity(o,manifest.meta.weights))]));const industries=manifest.industries.map(i=>({...i,opportunities:detail.get(i.slug)||[]}));return {meta:manifest.meta,industries};}

async function loadCities(){const atlas=await loadJson('/data/markets.json');const torontoManifest=await loadJson('/data/index.json');const torontoChunks=await Promise.all(torontoManifest.shards.map(s=>loadJson(`/data/${s}`)));const torontoOps=torontoChunks.flat().map(o=>normalizeCityOpportunity(o,torontoManifest.meta.weights));const cities=[];for(const country of atlas.countries){for(const city of country.cities){const ops=city.slug==='toronto'?torontoOps:(city.opportunities||[]).map(o=>normalizeCityOpportunity(o,atlas.weights));cities.push({...city,countryName:country.name,countrySlug:country.slug,opportunities:ops});}}return {cities,cityWeights:atlas.weights};}

function industryStats(ind,weights){const ops=[...ind.opportunities].sort((a,b)=>b.priorityScore-a.priorityScore);const avgMetrics={};for(const k of Object.keys(weights))avgMetrics[k]=avg(ops.map(o=>o.dimensions[k]||0));const profileScore=avg(ops.slice(0,Math.min(3,ops.length)).map(o=>o.priorityScore));return {...ind,ops,avgMetrics,profileScore,avgRisk:avg(ops.map(o=>o.riskPenalty||0)),avgConfidence:avg(ops.map(o=>o.confidence||0)),top:ops[0]};}
function cityContext(city,ind){let rel=city.opportunities.filter(o=>ind.affinity.includes(o.category));if(!rel.length)rel=city.opportunities;rel=[...rel].sort((a,b)=>b.priorityScore-a.priorityScore);const chosen=rel.slice(0,Math.min(3,rel.length));return {score:avg(chosen.map(o=>o.priorityScore)),relevant:rel,used:chosen};}
function intersection(city,indStat){const context=cityContext(city,indStat);return {city,industry:indStat,context,score:.70*indStat.profileScore+.30*context.score};}
function adjustedOpportunity(o,contextScore){return {...o,intersectionScore:.80*o.priorityScore+.20*contextScore};}
function cityIndustryPath(city,ind){return `${city.path.replace(/\/$/,'')}/industries/${ind.slug}`;}

function statHtml(items){return items.map(([v,l])=>`<div class="stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('');}
function sectorCard(s){return `<a class="industry-card" href="/industries/${esc(s.slug)}"><span class="industry-kicker">${s.ops.length} RESEARCHED PAINS</span><h3>${esc(s.name)}</h3><p>${esc(s.summary)}</p><div class="industry-card-meta"><span>${esc(s.top?.title||'Research in progress')}</span><strong>${s.profileScore.toFixed(1)}</strong></div></a>`;}

async function renderIndustryIndex(atlas,cities){const stats=atlas.industries.map(i=>industryStats(i,atlas.meta.weights));const all=stats.flatMap(s=>s.ops.map(o=>({...o,industry:s}))).sort((a,b)=>b.priorityScore-a.priorityScore);document.title='HAAM Pain - industry atlas';$('#industryStats').innerHTML=statHtml([[stats.length,'industries'],[all.length,'ranked pains'],[all.filter(o=>o.priorityScore>=80).length,'priority ≥ 80'],[all[0]?.priorityScore.toFixed(1)||'—','top opportunity']]);$('#footerMeta').textContent=`Industry research updated ${atlas.meta.researchedAt}. Scores are hypotheses.`;$('#industryGrid').innerHTML=stats.sort((a,b)=>b.profileScore-a.profileScore).map(sectorCard).join('');$('#industryLeaders').innerHTML=all.slice(0,15).map((o,i)=>`<a class="leader-row" href="/industries/${esc(o.industry.slug)}"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="place">${esc(o.industry.name)}</span><span class="pain-name">${esc(o.title)}</span><span class="score">${o.priorityScore.toFixed(1)}</span></a>`).join('');const sortedCities=cities.cities;$('#industryCityMatrix').innerHTML=`<div class="ic-row ic-head"><span>Industry</span>${sortedCities.map(c=>`<span>${esc(c.name)}</span>`).join('')}</div>${stats.sort((a,b)=>a.name.localeCompare(b.name)).map(s=>`<div class="ic-row"><a class="ic-name" href="/industries/${esc(s.slug)}">${esc(s.name)}</a>${sortedCities.map(c=>{const x=intersection(c,s);return `<a class="ic-cell" href="${esc(cityIndustryPath(c,s))}" title="Composite: 70% industry profile + 30% ${esc(c.name)} context">${x.score.toFixed(1)}<small>composite</small></a>`;}).join('')}</div>`).join('')}`;}

function opportunityRows(ops,scoreKey='priorityScore'){return ops.map((o,i)=>`<article class="industry-row" tabindex="0" role="button" data-id="${esc(o.id)}"><span class="industry-rank">${String(i+1).padStart(2,'0')}</span><div><span class="industry-mini">${scoreKey==='intersectionScore'?'COMPOSITE-ADJUSTED':'DIRECT INDUSTRY EVIDENCE'}</span><h3>${esc(o.title)}</h3><p>${esc(o.wedge)}</p><small>${esc(o.priceHypothesis||'')}</small></div><div class="industry-row-score"><strong>${o[scoreKey].toFixed(1)}</strong><span>${scoreKey==='intersectionScore'?'intersection':'priority'}</span><b>${o.dimensions.pain.toFixed(1)}</b><span>pain</span><b>${o.dimensions.economicLeverage.toFixed(1)}</b><span>econ leverage</span></div></article>`).join('');}

function openOpportunity(o,industry,displayScore=o.priorityScore,label='industry priority'){$('#industryDetail').innerHTML=`<article class="detail"><span class="detail-kicker">${esc(industry.name)} / DIRECT EVIDENCE</span><h2>${esc(o.title)}</h2><p>${esc(o.wedge)}</p><div class="detail-scoreline"><div><strong>${displayScore.toFixed(1)}</strong><span>${esc(label)}</span></div><div><strong>${o.dimensions.pain.toFixed(1)}</strong><span>pain</span></div><div><strong>${o.dimensions.frequency.toFixed(1)}</strong><span>frequency</span></div><div><strong>${o.dimensions.economicLeverage.toFixed(1)}</strong><span>econ leverage</span></div><div><strong>${o.confidence.toFixed(1)}/5</strong><span>confidence</span></div></div><div class="detail-block"><h3>Buyer</h3><p>${esc(o.buyer)}</p></div><div class="detail-block"><h3>Pain moment</h3><p>${esc(o.painMoment)}</p></div><div class="detail-block"><h3>First paid test</h3><p>${esc(o.firstTest)}</p></div><div class="detail-block"><h3>Price hypothesis</h3><p>${esc(o.priceHypothesis)}</p></div><div class="detail-block"><h3>Founder fit</h3><p>${esc(o.fitNote)}</p></div><div class="detail-block"><h3>Risks</h3><ul>${o.riskNotes.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div><div class="detail-block"><h3>Metrics</h3><div class="industry-metric-bars">${Object.entries(o.dimensions).map(([k,v])=>`<div><span>${esc(METRICS[k]||k)}</span><i><b style="width:${v/5*100}%"></b></i><strong>${v.toFixed(1)}</strong></div>`).join('')}</div></div><div class="detail-block"><h3>Evidence</h3><ul class="evidence-list">${o.evidence.map(e=>`<li><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.title)}</a><small>${esc(e.note||'')}</small></li>`).join('')}</ul></div></article>`;$('#industryDialog').showModal();}

async function renderIndustry(atlas,cities,slug){const ind=atlas.industries.find(i=>i.slug===slug);if(!ind)throw new Error('Unknown industry');const s=industryStats(ind,atlas.meta.weights);document.title=`HAAM Pain - ${ind.name}`;$('#industryEyebrow').textContent=`INDUSTRY / ${ind.name.toUpperCase()}`;$('#industryTitle').innerHTML=`${esc(ind.name)}<br><em>pain map.</em>`;$('#industryLede').textContent=ind.summary;$('#industryCompareLink').href=`/industries/compare?a=${encodeURIComponent(ind.slug)}`;$('#industryStats').innerHTML=statHtml([[s.ops.length,'ranked pains'],[s.profileScore.toFixed(1),'sector profile'],[s.avgMetrics.pain.toFixed(1)+'/5','average pain'],[s.avgMetrics.aiLeverage.toFixed(1)+'/5','AI leverage']]);$('#industryRanking').innerHTML=opportunityRows(s.ops);$('#industryRanking').querySelectorAll('.industry-row').forEach(row=>row.addEventListener('click',()=>openOpportunity(s.ops.find(o=>o.id===row.dataset.id),s)));const ints=cities.cities.map(c=>intersection(c,s)).sort((a,b)=>b.score-a.score);$('#industryCities').innerHTML=ints.map((x,i)=>`<a class="leader-row" href="${esc(cityIndustryPath(x.city,s))}"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="place">${esc(x.city.name)} <small>· ${esc(x.city.countryName)}</small></span><span class="pain-name">${esc(x.context.used[0]?.title||'city context')} <small>· composite</small></span><span class="score">${x.score.toFixed(1)}</span></a>`).join('');$('#industryWeights').innerHTML=Object.entries(atlas.meta.weights).map(([k,v])=>`<div class="weight"><strong>${v}</strong><span>${esc(METRICS[k]||k)}</span></div>`).join('');$('#footerMeta').textContent=`${ind.name} / researched ${atlas.meta.researchedAt}.`;$('#dialogClose')?.addEventListener('click',()=>$('#industryDialog').close());}

async function renderIntersection(atlas,cities,parts){const countrySlug=parts[0],citySlug=parts[1],industrySlug=parts[3];const city=cities.cities.find(c=>c.countrySlug===countrySlug&&c.slug===citySlug);const ind=atlas.industries.find(i=>i.slug===industrySlug);if(!city||!ind)throw new Error('Unknown city-industry intersection');const s=industryStats(ind,atlas.meta.weights);const x=intersection(city,s);const adjusted=s.ops.map(o=>adjustedOpportunity(o,x.context.score)).sort((a,b)=>b.intersectionScore-a.intersectionScore);document.title=`HAAM Pain - ${ind.name} in ${city.name}`;$('#intersectionEyebrow').textContent=`${city.name.toUpperCase()} × ${ind.name.toUpperCase()} / COMPOSITE`;$('#intersectionTitle').innerHTML=`${esc(ind.name)}<br><em>in ${esc(city.name)}.</em>`;$('#intersectionLede').textContent=`Where ${ind.name.toLowerCase()} pain could be especially attractive to attack in ${city.name}. ${ind.summary}`;$('#backIndustry').href=`/industries/${ind.slug}`;$('#backIndustry').textContent=ind.name;$('#backCity').href=city.path;$('#backCity').textContent=city.name;$('#intersectionStats').innerHTML=statHtml([[x.score.toFixed(1),'composite profile'],[x.context.score.toFixed(1),'city context'],[s.profileScore.toFixed(1),'industry profile'],['70 / 30','industry / city']]);$('#intersectionRanking').innerHTML=opportunityRows(adjusted,'intersectionScore');$('#intersectionRanking').querySelectorAll('.industry-row').forEach(row=>{const o=adjusted.find(q=>q.id===row.dataset.id);row.addEventListener('click',()=>openOpportunity(o,s,o.intersectionScore,'composite-adjusted'));});$('#cityContext').innerHTML=x.context.used.map(o=>`<a class="context-card" href="${esc(city.path)}"><span>${esc(o.category)}</span><h3>${esc(o.title)}</h3><strong>${o.priorityScore.toFixed(1)}</strong><p>Direct city opportunity feeding the 30% context component.</p></a>`).join('');$('#footerMeta').textContent=`Composite hypothesis: direct ${ind.name} research + direct ${city.name} context.`;$('#dialogClose')?.addEventListener('click',()=>$('#industryDialog').close());}

function metricGap(a,b){return Object.keys(METRICS).map(k=>({key:k,label:METRICS[k],a:a.avgMetrics[k],b:b.avgMetrics[k],gap:a.avgMetrics[k]-b.avgMetrics[k]})).sort((x,y)=>Math.abs(y.gap)-Math.abs(x.gap));}
function renderPair(a,b){$('#pairTitle').textContent=`${a.name} vs ${b.name}`;const gaps=metricGap(a,b);const biggest=gaps[0];$('#pairInsights').innerHTML=`<article class="context-card"><span>BIGGEST DIFFERENCE</span><h3>${esc(biggest.label)}</h3><strong>${biggest.gap>=0?'+':''}${biggest.gap.toFixed(1)}</strong><p>${esc(a.name)} ${biggest.gap>=0?'over-indexes':'under-indexes'} versus ${esc(b.name)} in the current research set.</p></article><article class="context-card"><span>PROFILE</span><h3>${esc(a.name)}</h3><strong>${a.profileScore.toFixed(1)}</strong><p>Leader: ${esc(a.top.title)}</p></article><article class="context-card"><span>PROFILE</span><h3>${esc(b.name)}</h3><strong>${b.profileScore.toFixed(1)}</strong><p>Leader: ${esc(b.top.title)}</p></article>`;$('#dimensionCompare').innerHTML=gaps.map(g=>`<div class="metric-compare-row"><span>${esc(g.label)}</span><div><i style="width:${g.a/5*100}%"></i><b>${g.a.toFixed(1)}</b></div><div><i style="width:${g.b/5*100}%"></i><b>${g.b.toFixed(1)}</b></div></div>`).join('');}

async function renderIndustryCompare(atlas){const stats=atlas.industries.map(i=>industryStats(i,atlas.meta.weights));const q=new URLSearchParams(location.search);let a=stats.find(s=>s.slug===q.get('a'))||stats.find(s=>s.slug==='architecture')||stats[0];let b=stats.find(s=>s.slug===q.get('b'))||stats.find(s=>s.slug==='medicine')||stats[1];const opts=stats.map(s=>`<option value="${esc(s.slug)}">${esc(s.name)}</option>`).join('');$('#industryA').innerHTML=opts;$('#industryB').innerHTML=opts;$('#industryA').value=a.slug;$('#industryB').value=b.slug;const update=()=>{a=stats.find(s=>s.slug===$('#industryA').value);b=stats.find(s=>s.slug===$('#industryB').value);history.replaceState(null,'',`/industries/compare?a=${encodeURIComponent(a.slug)}&b=${encodeURIComponent(b.slug)}`);renderPair(a,b);};$('#industryA').addEventListener('change',update);$('#industryB').addEventListener('change',update);renderPair(a,b);const cols=['profileScore','pain','frequency','economicLeverage','aiLeverage','founderFit'];$('#industryMatrix').innerHTML=`<div class="im-row im-head"><span>Industry</span><span>Profile</span><span>Pain</span><span>Frequency</span><span>Econ leverage</span><span>AI leverage</span><span>Founder fit</span><span>Risk</span></div>${stats.sort((x,y)=>y.profileScore-x.profileScore).map(s=>`<div class="im-row"><a href="/industries/${esc(s.slug)}">${esc(s.name)}</a><strong>${s.profileScore.toFixed(1)}</strong><span>${s.avgMetrics.pain.toFixed(1)}</span><span>${s.avgMetrics.frequency.toFixed(1)}</span><span>${s.avgMetrics.economicLeverage.toFixed(1)}</span><span>${s.avgMetrics.aiLeverage.toFixed(1)}</span><span>${s.avgMetrics.founderFit.toFixed(1)}</span><span>${s.avgRisk.toFixed(1)}</span></div>`).join('')}`;$('#footerMeta').textContent=`12 sectors / ${stats.reduce((n,s)=>n+s.ops.length,0)} direct industry opportunities.`;}

(async()=>{try{const atlas=await loadIndustryAtlas();const page=document.body.dataset.page;if(page==='industry-compare')return renderIndustryCompare(atlas);const cities=await loadCities();if(page==='industries')return renderIndustryIndex(atlas,cities);if(page==='industry')return renderIndustry(atlas,cities,location.pathname.split('/').filter(Boolean).pop());if(page==='industry-city')return renderIntersection(atlas,cities,location.pathname.split('/').filter(Boolean));}catch(err){console.error(err);document.body.innerHTML=`<main style="padding:10vw"><h1>Could not load industry research.</h1><pre>${esc(err.message)}</pre></main>`;}})();